# c2c-msg justfile - common development tasks
# Usage: just <recipe>

default:
    @just --list

# Install OCaml deps into the current opam switch.
# Keep in sync with the `depends` list in dune-project.
install-deps:
    opam install --yes dune cmdliner yojson lwt logs alcotest cohttp-lwt-unix uuidm \
        base64 digestif mirage-crypto-ec mirage-crypto-rng \
        tls-lwt mirage-crypto-rng-lwt ca-certs hacl-star sqlite3

# One-shot OCaml toolchain bootstrap: creates the 'c2c' opam switch if missing,
# then installs deps. Assumes opam + a system ocaml are already installed
# (e.g. `sudo pacman -S opam ocaml` on Arch, `sudo apt install opam` on Debian).
# Re-runs are idempotent.
setup-ocaml:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! command -v opam >/dev/null; then
        echo "opam not found — install it first (e.g. pacman -S opam ocaml)" >&2
        exit 1
    fi
    if [ ! -d "$HOME/.opam/repo" ] && [ ! -d "$HOME/.opam/default" ]; then
        opam init --bare --disable-sandboxing --no-setup --yes
    fi
    if ! opam switch list --short 2>/dev/null | grep -qx c2c; then
        opam switch create c2c --packages=ocaml-system --yes
    fi
    eval "$(opam env --switch=c2c --set-switch)"
    just install-deps

# Sync `.collab/skills/<name>.md` → `.claude/skills/<name>/SKILL.md` (#427).
# `.collab/skills/` is the tracked canonical home; `.claude/skills/` is the
# project-local copy that Claude Code loads as a Skill (gitignored). When
# the canonical changes, run `just sync-skills` to refresh the local copy.
# Idempotent; safe to run repeatedly. Codex skills (`~/.codex/skills/`) live
# outside the repo and are operator-managed.
sync-skills:
    #!/usr/bin/env bash
    set -euo pipefail
    src_dir=.collab/skills
    dst_dir=.claude/skills
    mkdir -p "$dst_dir"
    found=0
    for src in "$src_dir"/*.md; do
        [ -f "$src" ] || continue
        name=$(basename "$src" .md)
        mkdir -p "$dst_dir/$name"
        cp -f "$src" "$dst_dir/$name/SKILL.md"
        echo "synced: $src → $dst_dir/$name/SKILL.md"
        found=$((found + 1))
    done
    if [ "$found" = "0" ]; then
        echo "no skills found under $src_dir/" >&2
        exit 1
    fi

# Regenerate ocaml/cli/role_designer_embedded.ml from the canonical builtin.
# The binary embeds role-designer.md so `c2c agent refine` works in any
# checkout (and gracefully ignores missing/relocated files). Dune refuses to
# traverse dotfile dirs, so we preprocess outside dune.
codegen-role-designer:
    #!/usr/bin/env bash
    set -euo pipefail
    src=.c2c/roles/builtins/role-designer.md
    out=ocaml/cli/role_designer_embedded.ml
    if grep -Fq '|role_designer_src}' "$src"; then
        echo "error: role-designer.md contains the OCaml string delimiter '|role_designer_src}'" >&2
        echo "       pick a different delimiter in this recipe and update the embed." >&2
        exit 1
    fi
    {
        printf '(* AUTO-GENERATED by `just codegen-role-designer` from\n'
        printf '   .c2c/roles/builtins/role-designer.md. Do not edit by hand. *)\n\n'
        printf 'let content = {role_designer_src|'
        cat "$src"
        printf '|role_designer_src}\n'
    } > "$out.tmp"
    mv -f "$out.tmp" "$out"

# Regenerate ocaml/cli/role_templates_embedded.ml from the canonical
# role-class templates under .c2c/roles/builtins/templates/. Mirrors
# codegen-role-designer (#423). Embeds each template body verbatim so
# Path A (cold-start prompt) and Path B (agent new) emit canonical
# bodies with first-5-turns + peer-PASS + heartbeat block intact.
codegen-role-templates:
    #!/usr/bin/env bash
    set -euo pipefail
    src_dir=.c2c/roles/builtins/templates
    out=ocaml/cli/role_templates.ml
    delim=role_template_src
    if [ ! -d "$src_dir" ]; then
        echo "error: $src_dir/ not found" >&2
        exit 1
    fi
    {
        printf '(* AUTO-GENERATED by `just codegen-role-templates` from\n'
        printf '   .c2c/roles/builtins/templates/*.md.tmpl. Do not edit by hand.\n'
        printf '\n'
        printf '   Each entry is (role_class, raw_template_body). Substitution of\n'
        printf '   {alias} and {display_name_hint} is performed by the caller via\n'
        printf '   [Role_templates.render]; this module just embeds the source. *)\n\n'
        printf 'let templates : (string * string) list = [\n'
        for f in "$src_dir"/*.md.tmpl; do
            [ -f "$f" ] || continue
            base=$(basename "$f" .md.tmpl)
            if grep -Fq "|$delim}" "$f"; then
                echo "error: $f contains the OCaml string delimiter '|$delim}'" >&2
                echo "       pick a different delimiter in this recipe and update the embed." >&2
                exit 1
            fi
            printf '  ("%s", {%s|' "$base" "$delim"
            cat "$f"
            printf '|%s});\n' "$delim"
        done
        printf ']\n\n'
        printf 'let lookup role_class =\n'
        printf '  try Some (List.assoc role_class templates) with Not_found -> None\n\n'
        printf 'let render ~role_class ~alias ~display_name_hint =\n'
        printf '  match lookup role_class with\n'
        printf '  | None -> None\n'
        printf '  | Some body ->\n'
        printf '    let alias_re = Str.regexp_string "{alias}" in\n'
        printf '    let hint_re  = Str.regexp_string "{display_name_hint}" in\n'
        printf '    let body = Str.global_replace alias_re alias body in\n'
        printf '    let body = Str.global_replace hint_re  display_name_hint body in\n'
        printf '    Some body\n'
    } > "$out.tmp"
    mv -f "$out.tmp" "$out"

# Build the OCaml CLI binary and MCP server (full project)
# Note: this recipe intentionally builds ALL primary targets (c2c.exe + server + hooks)
# so that any compilation error causes a non-zero exit.
# For server-only fast builds use build-server; for CLI-only use build-cli.
#
# Per-worktree flock (#parallel-dune-softlock) serialises same-worktree
# concurrent builds while leaving cross-worktree builds parallel.
build: codegen-role-designer
    mkdir -p _build && touch _build/.c2c-build.lock
    flock _build/.c2c-build.lock scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" ./ocaml/cli/c2c.exe ./ocaml/server/c2c_mcp_server.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe ./ocaml/tools/c2c_post_compact_hook_bin.exe

# Build the OCaml CLI binary only (fast, for iterative CLI work)
build-cli: codegen-role-designer
    mkdir -p _build && touch _build/.c2c-build.lock
    flock _build/.c2c-build.lock scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" ./ocaml/cli/c2c.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe

# Build MCP server + hooks only (fast, for server/hook work)
build-server: codegen-role-designer
    mkdir -p _build && touch _build/.c2c-build.lock
    flock _build/.c2c-build.lock scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" ./ocaml/server/c2c_mcp_server.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe ./ocaml/tools/c2c_post_compact_hook_bin.exe

# Alias for build-all (back-compat)
build-all: build

# Run Python tests only
# --force-test-env bypasses the pre-flight process-count guard (needed when
# running alongside a live swarm; safe for CI where no swarm is running).
test-py:
    python3 -m pytest tests/ -q --tb=short --force-test-env

# Run OCaml tests only
test-ocaml:
    mkdir -p _build && touch _build/.c2c-build.lock
    flock _build/.c2c-build.lock scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune runtest --root "$PWD" ocaml/

# Run TypeScript (vitest) unit tests for the .opencode plugin
# Installs devDependencies on demand (idempotent if already installed).
test-ts:
    cd .opencode && npm install --no-audit --no-fund --silent && npx vitest run tests/

# Run the OpenCode plugin Python integration test (harness-driven)
test-ts-integration:
    python3 -m pytest tests/test_c2c_opencode_plugin_integration.py -v

# Run all tests (Python + OCaml + TS). Always rebuilds OCaml first to avoid stale binary.
test: build test-ocaml test-py test-ts

# Run a specific Python test file or pattern
# Usage: just test-one tests/test_c2c_history.py
#        just test-one -k "test_send"
test-one *ARGS:
    python3 -m pytest {{ARGS}} -v --tb=short

# Pre-flight check: catches latent breakage that `just build` (narrow
# target list) misses — specifically test exes that fall behind their
# imported APIs. Sister to `just test-ocaml` but skips the run cost.
# Also runs `git diff --check` for trailing whitespace.

# Run OCaml tests for a worktree slice.
# Usage: just test-slice .worktrees/my-slice
#
# Note: `dune runtest --root <worktree>/ocaml/` does NOT work from within
# a worktree (path resolution goes to main repo). Workaround: build from main
# repo first (run `just test-ocaml` once from the main repo to populate _build
# artifacts for all worktrees), then run binaries directly from each worktree's
# _build directory using this recipe.
#
# Known limitation: test_c2c_mcp has CWD-dependent temp-dir flakiness
# (temp dir name derived from cwd → collisions when binary runs from a
# different directory than where it was built). This is a pre-existing test
# issue; the binary is excluded from the pass/fail tally.
test-slice *SLICES:
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ {{SLICES}} == "" ]]; then
        echo "Usage: just test-slice .worktrees/<slice-name>" >&2
        exit 1
    fi
    for slice in {{SLICES}}; do
        echo "=== Testing slice: $slice ==="
        test_dir="$slice/_build/default/ocaml/test"
        if [[ ! -d "$test_dir" ]]; then
            echo "No _build found at $test_dir — run 'just test-ocaml' from main repo first to populate build artifacts" >&2
            continue
        fi
        total=0; passed=0; failed=0
        for exe in "$test_dir"/*.exe; do
            [[ -e "$exe" ]] || continue
            name=$(basename "$exe" .exe)
            # test_c2c_mcp has CWD-dependent temp-dir flakiness — skip
            [[ "$name" == "test_c2c_mcp" ]] && echo "[$name] SKIP (known CWD flakiness)" && continue
            total=$((total + 1))
            echo -n "[$name] "
            if "$exe" > /dev/null 2>&1; then
                echo "PASS"
                passed=$((passed + 1))
            else
                echo "FAIL"
                failed=$((failed + 1))
            fi
        done
        echo "=== $slice: $passed/$total passed, $failed failed ==="
    done

check:
    git diff --check
    mkdir -p _build && touch _build/.c2c-build.lock
    flock _build/.c2c-build.lock scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD"
    # #442: enforce broker-log-events.md catalog completeness — any new
    # `"event", `String "<name>"` emitter in ocaml/ must be cataloged.
    ./scripts/check-broker-log-catalog.sh

# Install repo git hooks (pre-commit: plugin syntax check).
# Uses symlinks so edits in scripts/git-hooks/ apply immediately.
#
# #436: must install into the repo-LOCAL hooks dir, NOT a global one.
# `git rev-parse --git-path hooks` honors `core.hooksPath`, which can
# be set globally (e.g. ~/.config/git/hooks) by other tooling — that
# silently redirected `just bi`'s hooks to the user's global path on
# fresh clones, breaking the repo-local pre-push coordinator gate.
# `--git-common-dir` returns the actual .git/ regardless of any
# hooksPath config, and is worktree-friendly (returns the main
# tree's .git/ for worktrees too — that's what we want; one set of
# hooks shared across all worktrees of a repo).
install-git-hooks:
    #!/usr/bin/env bash
    set -euo pipefail
    hooks_dir="$(git rev-parse --git-common-dir)/hooks"
    mkdir -p "$hooks_dir"
    for src in scripts/git-hooks/*; do
        name="$(basename "$src")"
        ln -sfn "$(realpath "$src")" "$hooks_dir/$name"
        echo "installed: $hooks_dir/$name → $src"
    done

# Install OCaml CLI binary to ~/.local/bin (build + copy)
# Routes through the shared flock+guard+stamp path (#322) so partial
# installs can't bypass the integrity guard.
install-cli:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/cli/c2c.exe
    mkdir -p ~/.local/bin
    flock ~/.local/bin/.c2c-install.lock bash -c '\
      set -euo pipefail; \
      scripts/c2c-install-guard.sh; \
      rm -f ~/.local/bin/c2c; \
      cp _build/default/ocaml/cli/c2c.exe ~/.local/bin/c2c; \
      scripts/c2c-install-stamp.sh; \
    '

# Install OCaml MCP server binary to ~/.local/bin (build + copy)
install-mcp:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/server/c2c_mcp_server.exe
    mkdir -p ~/.local/bin
    flock ~/.local/bin/.c2c-install.lock bash -c '\
      set -euo pipefail; \
      scripts/c2c-install-guard.sh; \
      rm -f ~/.local/bin/c2c-mcp-server; \
      cp _build/default/ocaml/server/c2c_mcp_server.exe ~/.local/bin/c2c-mcp-server; \
      scripts/c2c-install-stamp.sh; \
    '

# Install OCaml inbox hook binary to ~/.local/bin (build + copy)
install-hook:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/tools/c2c_inbox_hook.exe
    mkdir -p ~/.local/bin
    flock ~/.local/bin/.c2c-install.lock bash -c '\
      set -euo pipefail; \
      scripts/c2c-install-guard.sh; \
      rm -f ~/.local/bin/c2c-inbox-hook-ocaml; \
      cp _build/default/ocaml/tools/c2c_inbox_hook.exe ~/.local/bin/c2c-inbox-hook-ocaml; \
      scripts/c2c-install-stamp.sh; \
    '

# Install all OCaml binaries (CLI + MCP server + MCP inner + inbox hook)
# Build all first, then copy all; avoids half-updated state on build failure.
# Also installs git hooks (including pre-push coordinator gate).
install-all: codegen-role-designer install-git-hooks
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/cli/c2c.exe ./ocaml/cli/c2c_deliver_inbox.exe ./ocaml/server/c2c_mcp_server.exe ./ocaml/server/c2c_mcp_server_inner_bin.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe ./ocaml/tools/c2c_post_compact_hook_bin.exe
    # Guard + atomic install + stamp under a single flock so concurrent
    # `just bi` runs from different worktrees can't race past the guard
    # then clobber each other. See scripts/c2c-install-guard.sh (#302).
    mkdir -p ~/.local/bin
    flock ~/.local/bin/.c2c-install.lock bash -c '\
      set -euo pipefail; \
      scripts/c2c-install-guard.sh; \
      scripts/c2c-install-live-holders.sh; \
      rm -f ~/.local/bin/c2c ~/.local/bin/c2c-mcp-server ~/.local/bin/c2c-mcp-inner ~/.local/bin/c2c-inbox-hook-ocaml ~/.local/bin/c2c-cold-boot-hook ~/.local/bin/c2c-post-compact-hook ~/.local/bin/cc-quota ~/.local/bin/c2c-deliver-inbox; \
      cp _build/default/ocaml/cli/c2c.exe ~/.local/bin/c2c; \
      cp _build/default/ocaml/server/c2c_mcp_server.exe ~/.local/bin/c2c-mcp-server; \
      cp _build/default/ocaml/server/c2c_mcp_server_inner_bin.exe ~/.local/bin/c2c-mcp-inner; \
      cp _build/default/ocaml/tools/c2c_inbox_hook.exe ~/.local/bin/c2c-inbox-hook-ocaml; \
      cp _build/default/ocaml/tools/c2c_cold_boot_hook.exe ~/.local/bin/c2c-cold-boot-hook; \
      cp _build/default/ocaml/tools/c2c_post_compact_hook_bin.exe ~/.local/bin/c2c-post-compact-hook; \
      printf "#!/usr/bin/env bash\nset -euo pipefail\nexec \"%s/scripts/cc-quota\" \"\$@\"\n" "$PWD" > ~/.local/bin/cc-quota; \
      chmod +x ~/.local/bin/cc-quota; \
      cp _build/default/ocaml/cli/c2c_deliver_inbox.exe ~/.local/bin/c2c-deliver-inbox; \
      chmod +x ~/.local/bin/c2c-deliver-inbox; \
      scripts/c2c-install-stamp.sh; \
    '

# Primary install path: current OCaml binaries only
install: install-all

# Back-compat alias for agents that still try the old Rust-era recipe name
install-rs: install-all

# Shorthand: build + install current OCaml binaries in one shot
bi: install-all

# Build CLI, install, then restart self to pick up new binary
bii: install-all
    ./restart-self

# Legacy: install Python wrapper scripts to ~/.local/bin
install-python-legacy:
    python3 c2c_install.py

# Quick c2c broker status
status:
    c2c health

# Clean dune build artifacts
clean:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune clean

# Local relay in docker-compose. See .collab/runbooks/local-relay.md.
relay-up:
    DOCKER_BUILDKIT=1 docker compose up -d --build
    @echo "Waiting for relay to be healthy..."
    @for i in 1 2 3 4 5 6 7 8 9 10; do \
        if curl -fsS http://localhost:7331/health >/dev/null 2>&1; then echo "relay up at http://localhost:7331"; exit 0; fi; \
        sleep 2; \
    done; echo "relay did not become healthy within 20s; check 'just relay-logs'" >&2; exit 1

relay-down:
    docker compose down

# Railway deploy-path gate: docker build → run → health → EACCES perm-degrade.
# Runs the relay inside a docker container exactly as Railway would, asserting
# it starts cleanly and degrades gracefully under a read-only /data volume.
# See scripts/relay-deploy-test.sh for deferred items (dead-letter, mesh, token).
relay-deploy-test:
    #!/usr/bin/env bash
    set -euo pipefail
    exec scripts/relay-deploy-test.sh

relay-reset:
    docker compose down -v

relay-logs:
    docker compose logs -f relay

# GUI dev server (requires webkit2gtk-4.1: sudo pacman -S webkit2gtk-4.1)
gui-dev:
    cd gui && bun run tauri dev

# GUI production build check
gui-check:
    cd gui && bun run build

# Run Playwright E2E tests for the GUI.
# Requires browsers to be installed: bunx playwright install chromium
# Requires the Tauri dev server to be running OR uses the webServer config in playwright.config.ts
gui-e2e:
    cd gui && bunx playwright test

# Stage and commit all staged changes with a message
# Usage: just gc "fix: something"
gc *MSG:
    git add -A && git commit -m {{MSG}}

# Stage and commit specific files with a message
# Usage: just gac "fix: something" ocaml/c2c_start.ml
gac MSG FILES:
    git add {{FILES}} && git commit -m {{MSG}}

# Stage and commit .collab/findings/ and .collab/updates/ explicitly (gitignored to suppress ?? noise)
# Usage: just collab-commit "findings: describe what you found"
collab-commit MSG:
    git add -f .collab/findings/ .collab/updates/ && git commit -m {{ quote(MSG) }}
