# c2c-msg justfile - common development tasks
# Usage: just <recipe>

default:
    @just --list

# Install OCaml deps into the current opam switch.
# Keep in sync with the `depends` list in dune-project.
install-deps:
    opam install --yes dune cmdliner yojson lwt logs alcotest cohttp-lwt-unix uuidm

# One-shot OCaml toolchain bootstrap: creates the 'c2c' opam switch if missing,
# then installs deps. Assumes opam + a system ocaml are already installed
# (e.g. `sudo pacman -S opam ocaml` on Arch, `sudo apt install opam` on Debian).
# Re-runs are idempotent.
setup-ocaml:
    #!/usr/bin/env bash
    set -euo pipefail
    if ! command -v opam >/dev/null; then
        echo "opam not found — install it first (e.g. pacman -S opam ocaml)" >&2
        exit 1
    fi
    if [ ! -d "$HOME/.opam/repo" ] && [ ! -d "$HOME/.opam/default" ]; then
        opam init --bare --disable-sandboxing --no-setup --yes
    fi
    if ! opam switch list --short 2>/dev/null | grep -qx c2c; then
        opam switch create c2c --packages=ocaml-system --yes
    fi
    eval "$(opam env --switch=c2c --set-switch)"
    just install-deps

# Regenerate ocaml/cli/role_designer_embedded.ml from the canonical builtin.
# The binary embeds role-designer.md so `c2c agent refine` works in any
# checkout (and gracefully ignores missing/relocated files). Dune refuses to
# traverse dotfile dirs, so we preprocess outside dune.
codegen-role-designer:
    #!/usr/bin/env bash
    set -euo pipefail
    src=.c2c/roles/builtins/role-designer.md
    out=ocaml/cli/role_designer_embedded.ml
    if grep -Fq '|role_designer_src}' "$src"; then
        echo "error: role-designer.md contains the OCaml string delimiter '|role_designer_src}'" >&2
        echo "       pick a different delimiter in this recipe and update the embed." >&2
        exit 1
    fi
    {
        printf '(* AUTO-GENERATED by `just codegen-role-designer` from\n'
        printf '   .c2c/roles/builtins/role-designer.md. Do not edit by hand. *)\n\n'
        printf 'let content = {role_designer_src|'
        cat "$src"
        printf '|role_designer_src}\n'
    } > "$out.tmp"
    mv -f "$out.tmp" "$out"

# Build the OCaml MCP server
build: codegen-role-designer
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" ./ocaml/server/c2c_mcp_server.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe

# Build the OCaml CLI binary
build-cli: codegen-role-designer
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" ./ocaml/cli/c2c.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe

# Build both MCP server and CLI
build-all: build build-cli

# Run Python tests only
# --force-test-env bypasses the pre-flight process-count guard (needed when
# running alongside a live swarm; safe for CI where no swarm is running).
test-py:
    python3 -m pytest tests/ -q --tb=short --force-test-env

# Run OCaml tests only
test-ocaml:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune runtest --root "$PWD" ocaml/

# Run TypeScript (vitest) unit tests for the .opencode plugin
# Installs devDependencies on demand (idempotent if already installed).
test-ts:
    cd .opencode && npm install --no-audit --no-fund --silent && npx vitest run tests/

# Run the OpenCode plugin Python integration test (harness-driven)
test-ts-integration:
    python3 -m pytest tests/test_c2c_opencode_plugin_integration.py -v

# Run all tests (Python + OCaml + TS). Always rebuilds OCaml first to avoid stale binary.
test: build test-ocaml test-py test-ts

# Run a specific Python test file or pattern
# Usage: just test-one tests/test_c2c_history.py
#        just test-one -k "test_send"
test-one *ARGS:
    python3 -m pytest {{ARGS}} -v --tb=short

# Format check: verify no trailing whitespace in Python files
check:
    git diff --check

# Install repo git hooks (pre-commit: plugin syntax check).
# Uses symlinks so edits in scripts/git-hooks/ apply immediately.
install-git-hooks:
    #!/usr/bin/env bash
    set -euo pipefail
    hooks_dir="$(git rev-parse --git-path hooks)"
    mkdir -p "$hooks_dir"
    for src in scripts/git-hooks/*; do
        name="$(basename "$src")"
        ln -sfn "$(realpath "$src")" "$hooks_dir/$name"
        echo "installed: $hooks_dir/$name → $src"
    done

# Install OCaml CLI binary to ~/.local/bin (build + copy)
install-cli:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/cli/c2c.exe
    rm -f ~/.local/bin/c2c
    cp _build/default/ocaml/cli/c2c.exe ~/.local/bin/c2c

# Install OCaml MCP server binary to ~/.local/bin (build + copy)
install-mcp:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/server/c2c_mcp_server.exe
    rm -f ~/.local/bin/c2c-mcp-server
    cp _build/default/ocaml/server/c2c_mcp_server.exe ~/.local/bin/c2c-mcp-server

# Install OCaml inbox hook binary to ~/.local/bin (build + copy)
install-hook:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/tools/c2c_inbox_hook.exe
    rm -f ~/.local/bin/c2c-inbox-hook-ocaml
    cp _build/default/ocaml/tools/c2c_inbox_hook.exe ~/.local/bin/c2c-inbox-hook-ocaml

# Install all OCaml binaries (CLI + MCP server + inbox hook)
# Build all first, then copy all; avoids half-updated state on build failure.
# Also installs git hooks (including pre-push coordinator gate).
install-all: codegen-role-designer install-git-hooks
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune build --root "$PWD" -j1 ./ocaml/cli/c2c.exe ./ocaml/server/c2c_mcp_server.exe ./ocaml/tools/c2c_inbox_hook.exe ./ocaml/tools/c2c_cold_boot_hook.exe
    rm -f ~/.local/bin/c2c ~/.local/bin/c2c-mcp-server ~/.local/bin/c2c-inbox-hook-ocaml ~/.local/bin/c2c-cold-boot-hook ~/.local/bin/cc-quota
    cp _build/default/ocaml/cli/c2c.exe ~/.local/bin/c2c
    cp _build/default/ocaml/server/c2c_mcp_server.exe ~/.local/bin/c2c-mcp-server
    cp _build/default/ocaml/tools/c2c_inbox_hook.exe ~/.local/bin/c2c-inbox-hook-ocaml
    cp _build/default/ocaml/tools/c2c_cold_boot_hook.exe ~/.local/bin/c2c-cold-boot-hook
    printf '#!/usr/bin/env bash\nset -euo pipefail\nexec "%s/scripts/cc-quota" "$@"\n' "$PWD" > ~/.local/bin/cc-quota
    chmod +x ~/.local/bin/cc-quota

# Primary install path: current OCaml binaries only
install: install-all

# Back-compat alias for agents that still try the old Rust-era recipe name
install-rs: install-all

# Shorthand: build + install current OCaml binaries in one shot
bi: install-all

# Build CLI, install, then restart self to pick up new binary
bii: install-all
    ./restart-self

# Legacy: install Python wrapper scripts to ~/.local/bin
install-python-legacy:
    python3 c2c_install.py

# Quick c2c broker status
status:
    c2c health

# Clean dune build artifacts
clean:
    scripts/dune-watchdog.sh ${DUNE_WATCHDOG_TIMEOUT:-60} opam exec -- dune clean

# Local relay in docker-compose. See .collab/runbooks/local-relay.md.
relay-up:
    DOCKER_BUILDKIT=1 docker compose up -d --build
    @echo "Waiting for relay to be healthy..."
    @for i in 1 2 3 4 5 6 7 8 9 10; do \
        if curl -fsS http://localhost:7331/health >/dev/null 2>&1; then echo "relay up at http://localhost:7331"; exit 0; fi; \
        sleep 2; \
    done; echo "relay did not become healthy within 20s; check 'just relay-logs'" >&2; exit 1

relay-down:
    docker compose down

relay-reset:
    docker compose down -v

relay-logs:
    docker compose logs -f relay

# GUI dev server (requires webkit2gtk-4.1: sudo pacman -S webkit2gtk-4.1)
gui-dev:
    cd gui && bun run tauri dev

# GUI production build check
gui-check:
    cd gui && bun run build

# Stage and commit all staged changes with a message
# Usage: just gc "fix: something"
gc *MSG:
    git add -A && git commit -m {{MSG}}

# Stage and commit specific files with a message
# Usage: just gac "fix: something" ocaml/c2c_start.ml
gac MSG FILES:
    git add {{FILES}} && git commit -m {{MSG}}

# Stage and commit .collab/findings/ and .collab/updates/ explicitly (gitignored to suppress ?? noise)
# Usage: just collab-commit "findings: describe what you found"
collab-commit MSG:
    git add -f .collab/findings/ .collab/updates/ && git commit -m {{ quote(MSG) }}
