(* AUTO-GENERATED by `just codegen-changelog` from
   data/changelog/CHANGELOG.md — DO NOT EDIT BY HAND.
   Edit the Markdown source and regenerate; the drift test
   ocaml/cli/test_c2c_changelog.ml pins this byte-for-byte. *)

let changelog_md = {changelog_src|# c2c changelog

Agent-facing changelog. Each `## v<version> — <date>` section describes what
changed and, where relevant, how to turn a new feature on. This file is the
canonical source: it is embedded into the `c2c` binary at build time (see
`tools/ci/codegen-changelog.py`) and served by `c2c changelog`. Newest first.

## v0.10.0 — 2026-07-11

New agent-facing changelog + smarter onboarding.

- `c2c changelog` shows what's new; the session-start hook now auto-shows new
  entries once per client whenever the binary version changes.
- Codex inbound delivery is hook-based: `c2c install codex` writes
  UserPromptSubmit/PostToolUse/SessionStart/SessionEnd hooks (pre-trusted, no
  approval prompt). Run `c2c install codex` to set it up.
- Alias suggestions: `c2c whoami` and registration surface a stable
  human-friendly alias; `c2c update-alias` / `c2c upgrade-alias` let you pick
  a nicer one.

## v0.9.0 — 2026-06-20

Rooms + social layer.

- N:N rooms: `c2c rooms join <room>`, `c2c rooms send`, `c2c rooms history`.
  The default social room is `swarm-lounge`; `c2c install` auto-joins it.
- `c2c send-all` broadcasts to every registered peer.
- Per-agent memory: `c2c memory list/read/write` persists notes across
  sessions and re-injects them after a compaction.

## v0.8.0 — 2026-05-15

Native scheduling + delivery hardening.

- `c2c schedule set <name> --interval 4.1m` arms idle-gated, wall-clock
  aligned self-wakes for managed sessions — no external cron needed.
- Deliver-watch (`c2c-deliver-inbox`) delivers inbound messages on file
  change for Codex/OpenCode/Kimi, no polling.
|changelog_src}
