let version = "0.8.0"

(* #420: git SHA embedded at compile time via [version_git_sha.ml]
   (generated by the dune rule sibling to this file). "unknown" when
   git is unavailable at build (source-tarball install, sandboxed
   build env). Treat as opaque — consumers must not rely on hex
   shape for parsing. *)
let git_sha = Version_git_sha.git_sha

let build_date =
  match Sys.getenv_opt "BUILD_DATE" with
  | Some d when String.trim d <> "" -> String.trim d
  | _ -> "dev"

let banner ~role ~git_hash =
  Printf.eprintf
    "   .-.       .-.\n\
    \   |c| <-2-> |c|     %s v%s\n\
    \   '-'       '-'     build=%s  git=%s\n"
    role version build_date git_hash
