let version = "0.14.0"

(* Relay wire protocol version (B121). Independent of the package
   [version] string: bump when the client↔relay HTTP/JSON wire becomes
   incompatible (auth scheme, envelope shape, required fields, etc.).
   Server advertises this on GET /health; clients compare and surface an
   upgrade message instead of opaque signature_invalid/bad_request errors.
   [relay_min_client_protocol_version] is server-side policy for the
   oldest client protocol still accepted — keep equal to
   [relay_protocol_version] for a hard cut, or lower while supporting
   a window of older clients. *)
let relay_protocol_version = 1
let relay_min_client_protocol_version = 1

(* #420: git SHA embedded at compile time via [version_git_sha.ml]
   (generated by the dune rule sibling to this file). "unknown" when
   git is unavailable at build (source-tarball install, sandboxed
   build env). Treat as opaque — consumers must not rely on hex
   shape for parsing. *)
let git_sha = Version_git_sha.git_sha

let build_date = Version_build_date.build_date

let banner ~role ~git_hash =
  Printf.eprintf
    "   .-.       .-.\n\
    \   |c| <-2-> |c|     %s v%s\n\
    \   '-'       '-'     build=%s  git=%s\n"
    role version build_date git_hash
