let version = "0.15.0"

(* Relay wire protocol version (B121). Independent of the package
   [version] string: bump when the client↔relay HTTP/JSON wire becomes
   incompatible (auth scheme, envelope shape, required fields, etc.).
   Server advertises this on GET /health; clients compare and surface an
   upgrade message instead of opaque signature_invalid/bad_request errors.
   [relay_min_client_protocol_version] is server-side policy for the
   oldest client protocol still accepted — keep equal to
   [relay_protocol_version] for a hard cut, or lower while supporting
   a window of older clients. *)
let relay_protocol_version = 1
let relay_min_client_protocol_version = 1

(* #420: git SHA embedded at compile time via [version_git_sha.ml]
   (generated by the dune rule sibling to this file). "unknown" when
   git is unavailable at build (source-tarball install, sandboxed
   build env). Treat as opaque — consumers must not rely on hex
   shape for parsing. *)
let git_sha = Version_git_sha.git_sha

let build_date = Version_build_date.build_date

(* B287: the primary version identity uses BUILD time (a compile-time
   constant), never the wall clock at invocation. The old `--version` line
   embedded [C2c_time.now_iso8601_utc ()] as its trailing timestamp, so the
   "version" of the binary appeared to change every time you asked for it —
   a wall-clock echo masquerading as build metadata.

   Layout keeps the leading tokens stable and parseable for scripts:
     <version> [<git-sha>] (built <build-date>)
   e.g. "0.14.4 a1b2c3d4 (built 2026-07-24)". The git sha is omitted when
   unknown (source-tarball / sandboxed build). *)
let build_identity () =
  match git_sha with
  | "unknown" | "" -> Printf.sprintf "%s (built %s)" version build_date
  | h -> Printf.sprintf "%s %s (built %s)" version h build_date

(* B287: optional diagnostic wall clock. The bug allows keeping a "now" clock
   only if it is secondary and visually demarcated off to the side — the
   PRIMARY timestamp must be the build date above. This appends the current
   UTC instant in a bracketed, labelled segment so it can never be mistaken
   for the build metadata. [now] is injectable for deterministic tests. *)
let display_with_clock ?now () =
  let now = match now with Some n -> n | None -> C2c_time.now_iso8601_utc () in
  Printf.sprintf "%s   [now: %s]" (build_identity ()) now

let banner ~role ~git_hash =
  Printf.eprintf
    "   .-.       .-.\n\
    \   |c| <-2-> |c|     %s v%s\n\
    \   '-'       '-'     build=%s  git=%s\n"
    role version build_date git_hash
