#!/usr/bin/env python3
"""Regenerate ocaml/c2c_alias_words.ml from the alias word data files (B112).

Single source of truth:
  data/c2c_alias_words.txt       — full alias pool (one word per line, sorted)
  data/c2c_alias_words_easy.txt  — curated easy-to-type/read subset

Every word must be lowercase alphanumeric starting with a letter, 3..12
chars (hyphen is the alias separator, so words must never contain one),
sorted and unique; the easy pool must be a STRICT subset of the full pool.
The OCaml drift test (ocaml/test/test_c2c_alias_words.ml) pins the
embedded arrays byte-for-byte to these files.

Content policy (B112 review): aliases are public agent identities, so the
pool must stay family-friendly. Exclude any word with a dictionary-labeled
offensive/derogatory sense targeting people or groups — even when an
innocent primary sense exists (removed on review: kink, paddy, pansy,
spade, tramp, welch, tart, fruit, buck, broad, queen, tinker, yellow,
slant, slope, native). Words with mild vulgar slang senses that do NOT
target people or groups and whose primary meaning is overwhelmingly
innocent (e.g. root, screw, whip, master) are allowed. Apply the same bar
to any future additions.

Usage:
  python3 tools/ci/codegen-alias-words.py           # regenerate
  python3 tools/ci/codegen-alias-words.py --check   # exit 1 if output is stale
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
FULL_SRC = REPO_ROOT / "data" / "c2c_alias_words.txt"
EASY_SRC = REPO_ROOT / "data" / "c2c_alias_words_easy.txt"
OUT = REPO_ROOT / "ocaml" / "c2c_alias_words.ml"

WORD_RE = re.compile(r"^[a-z][a-z0-9]{2,11}$")
WORDS_PER_LINE = 10


def load_words(path: Path) -> list[str]:
    words = [line.strip() for line in path.read_text().splitlines() if line.strip()]
    errors = []
    for w in words:
        if not WORD_RE.fullmatch(w):
            errors.append(f"invalid word (must match {WORD_RE.pattern}): {w!r}")
    if words != sorted(words):
        errors.append(f"{path} is not sorted")
    if len(set(words)) != len(words):
        dupes = sorted({w for w in words if words.count(w) > 1})
        errors.append(f"duplicate words in {path}: {dupes}")
    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
    return words


def ocaml_array(name: str, words: list[str], doc: str) -> str:
    lines = [doc, f"let {name} = [|"]
    for i in range(0, len(words), WORDS_PER_LINE):
        chunk = "; ".join(f'"{w}"' for w in words[i : i + WORDS_PER_LINE])
        sep = ";" if i + WORDS_PER_LINE < len(words) else ""
        lines.append(f"    {chunk}{sep}")
    lines.append("  |]")
    return "\n".join(lines)


def render(full: list[str], easy: list[str]) -> str:
    n, e = len(full), len(easy)
    header = f"""(* AUTO-GENERATED by `just codegen-alias-words` from
   data/c2c_alias_words.txt and data/c2c_alias_words_easy.txt.
   Do not edit by hand — edit the data files and regenerate.

   Single canonical home for the alias word pool (#388 converged the
   duplicated literals from c2c_start.ml and cli/c2c_setup.ml; B112
   expanded the pool from 131 to {n} words). Cartesian product gives
   {n * (n - 1):,} ordered non-identical pairs. Words are lowercase
   alphanumeric, 3..12 chars, never contain '-' (the alias separator);
   drift vs the data files is pinned by test_c2c_alias_words.ml. *)
"""
    words_doc = f"(* Full pool — {n} words. *)"
    easy_doc = (
        f"(* easy_pool — {e} curated English-readable nature-themed words, a\n"
        f"   strict subset of [words]. Used for --easy-pool alias generation;\n"
        f"   cartesian product gives {e * (e - 1):,} ordered non-identical pairs. *)"
    )
    return (
        header
        + "\n"
        + ocaml_array("words", full, words_doc)
        + "\n\n"
        + ocaml_array("easy_pool", easy, easy_doc)
        + "\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="verify output is current")
    args = ap.parse_args()

    full = load_words(FULL_SRC)
    easy = load_words(EASY_SRC)
    missing = sorted(set(easy) - set(full))
    if missing:
        print(f"error: easy-pool words missing from full pool: {missing}", file=sys.stderr)
        return 1
    if len(easy) >= len(full):
        print(
            f"error: easy pool must be a STRICT subset of the full pool "
            f"(easy={len(easy)} >= full={len(full)})",
            file=sys.stderr,
        )
        return 1
    if len(full) < 1000:
        print(f"error: full pool too small ({len(full)} < 1000)", file=sys.stderr)
        return 1

    rendered = render(full, easy)
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print(f"error: {OUT} is stale — run `just codegen-alias-words`", file=sys.stderr)
            return 1
        print(f"ok: {OUT} is current ({len(full)} words, {len(easy)} easy)")
        return 0

    OUT.write_text(rendered)
    print(f"wrote {OUT} ({len(full)} words, {len(easy)} easy)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
