#!/usr/bin/env python3
"""Regenerate ocaml/cli/c2c_changelog_embedded.ml from data/changelog/CHANGELOG.md (B126).

Single source of truth:
  data/changelog/CHANGELOG.md — agent-facing changelog, one `## v<ver> — <date>`
  section per version, newest first.

The whole file is embedded verbatim as an OCaml quoted-string literal so the
`c2c` binary can serve `c2c changelog` and the session-start auto-show with
zero latency (no network for versions the binary was built with). The runtime
parser lives in ocaml/cli/c2c_changelog.ml; a drift test
(ocaml/cli/test_c2c_changelog.ml) pins this output byte-for-byte to the source.

Usage:
  python3 tools/ci/codegen-changelog.py           # regenerate
  python3 tools/ci/codegen-changelog.py --check    # exit 1 if output is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "data" / "changelog" / "CHANGELOG.md"
OUT = REPO_ROOT / "ocaml" / "cli" / "c2c_changelog_embedded.ml"

# OCaml quoted-string delimiter: {DELIM|...|DELIM}. Must be lowercase letters
# and underscores only (no digits — OCaml rejects them). Content must not
# contain the closing sequence "|DELIM}"; chosen to be unlikely in prose.
DELIM = "changelog_src"


def render(md: str) -> str:
    closing = "|" + DELIM + "}"
    if closing in md:
        print(
            f"error: {SRC} contains the reserved OCaml string delimiter "
            f"{closing!r}; change the delimiter in codegen-changelog.py.",
            file=sys.stderr,
        )
        sys.exit(1)
    header = (
        "(* AUTO-GENERATED by `just codegen-changelog` from\n"
        "   data/changelog/CHANGELOG.md — DO NOT EDIT BY HAND.\n"
        "   Edit the Markdown source and regenerate; the drift test\n"
        "   ocaml/cli/test_c2c_changelog.ml pins this byte-for-byte. *)\n\n"
    )
    return f"{header}let changelog_md = {{{DELIM}|{md}|{DELIM}}}\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if output is stale")
    args = ap.parse_args()

    if not SRC.exists():
        print(f"error: missing source {SRC}", file=sys.stderr)
        return 1
    md = SRC.read_text(encoding="utf-8")
    generated = render(md)

    if args.check:
        existing = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if existing != generated:
            print(
                f"error: {OUT} is stale — run `just codegen-changelog`",
                file=sys.stderr,
            )
            return 1
        return 0

    OUT.write_text(generated, encoding="utf-8")
    print(f"wrote {OUT} ({len(md)} bytes of changelog)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
