#!/usr/bin/env python3
"""Assemble per-harness c2c skills from snippets and embed into OCaml.

Sources:
  .collab/skills/c2c-src/harness/<name>.md
  .collab/skills/c2c-src/fragments/*.md  (sorted)

Outputs:
  .collab/skills/assembled/<name>.md
  .collab/skills/c2c.md                 (copy of assembled/default.md)
  ocaml/cli/c2c_claude_skill_embedded.ml  (default harness; claude/codex install)
  ocaml/cli/c2c_grok_skill_embedded.ml    (grok harness)
  ocaml/cli/c2c_kimi_skill_embedded.ml    (kimi harness)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / ".collab" / "skills" / "c2c-src"
HARNESS_DIR = SRC / "harness"
FRAG_DIR = SRC / "fragments"
ASSEMBLED_DIR = ROOT / ".collab" / "skills" / "assembled"
CANONICAL_DEFAULT = ROOT / ".collab" / "skills" / "c2c.md"
CLI = ROOT / "ocaml" / "cli"

# harness name -> (ml filename, ocaml delim, header comment path label)
EMBEDS = {
    "default": (
        "c2c_claude_skill_embedded.ml",
        "claude_skill_src",
        "assembled default harness (claude/codex install blob)",
    ),
    "grok": (
        "c2c_grok_skill_embedded.ml",
        "grok_skill_src",
        "assembled grok harness",
    ),
    "agy": (
        "c2c_agy_skill_embedded.ml",
        "agy_skill_src",
        "assembled agy harness",
    ),
    "kimi": (
        "c2c_kimi_skill_embedded.ml",
        "kimi_skill_src",
        "assembled kimi harness",
    ),
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def fragments() -> list[Path]:
    if not FRAG_DIR.is_dir():
        return []
    return sorted(p for p in FRAG_DIR.glob("*.md") if p.is_file())


def assemble(harness_name: str) -> str:
    harness_path = HARNESS_DIR / f"{harness_name}.md"
    if not harness_path.is_file():
        raise SystemExit(f"missing harness: {harness_path}")
    parts = [read_text(harness_path).rstrip() + "\n"]
    for frag in fragments():
        parts.append("\n" + read_text(frag).rstrip() + "\n")
    body = "".join(parts)
    if not body.endswith("\n"):
        body += "\n"
    return body


def embed_ml(content: str, delim: str, label: str) -> str:
    if f"|{delim}}}" in content:
        raise SystemExit(
            f"assembled skill contains OCaml delimiter '|{delim}}}' — change delim"
        )
    header = (
        f"(* AUTO-GENERATED by tools/ci/codegen-c2c-skills.py from\n"
        f"   {label}. Do not edit by hand. *)\n\n"
    )
    return f"{header}let content = {{{delim}|{content}|{delim}}}\n"


def main() -> int:
    harnesses = sorted(p.stem for p in HARNESS_DIR.glob("*.md") if p.is_file())
    if not harnesses:
        print("error: no harness files under", HARNESS_DIR, file=sys.stderr)
        return 1

    for name in harnesses:
        body = assemble(name)
        out = ASSEMBLED_DIR / f"{name}.md"
        write_text(out, body)
        print(f"wrote {out.relative_to(ROOT)} ({len(body)} bytes)")

        if name == "default":
            write_text(CANONICAL_DEFAULT, body)
            print(f"wrote {CANONICAL_DEFAULT.relative_to(ROOT)}")

        if name in EMBEDS:
            ml_name, delim, label = EMBEDS[name]
            ml_path = CLI / ml_name
            write_text(ml_path, embed_ml(body, delim, label))
            print(f"wrote {ml_path.relative_to(ROOT)}")

    # Require embeds for known install targets
    for required in EMBEDS:
        if required not in harnesses:
            print(f"error: missing required harness {required}", file=sys.stderr)
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
